<script lang="ts">
    import {onMount} from "svelte";
    import Task from '$lib/Task.svelte'
    import Create from '$lib/Create.svelte'
    import "../app.css";

    import {tasks} from '$lib/store.ts'

    onMount(() => {
        fetch("https://codeball-mvc.fly.dev/tasks")
            .then(res => res.json())
            .then(data => {
                tasks.set(data)
            })
    })

    let sortedTasks = []
    tasks.subscribe(tasks => {
        sortedTasks = tasks?.sort((a, b) => a.done - b.done) || []
    })
</script>

<div class="flex flex-col items-center space-y-8 p-9">

    <h1 class="text-3xl font-bold">Codeball Todo MVC</h1>

    <div class="flex w-full justify-around">
        {#if sortedTasks}
            <div class="space-y-4 max-w-prose w-full">
                <Create/>
                {#each sortedTasks as task}
                    <Task {task}/>
                {/each}
            </div>
        {/if}
    </div>

    <p class="text-gray-400">
        The backend for this project was generated by <a href="https://codeball.ai/" class="text-gray-800">Codeball</a> and OpenAI Codex. <br> The database
        resets every 15 minutes. Be nice! 🙏 <br><br>
        &mdash; A Codeball Project 🧠<br><br>
        <a href="https://codeball.ai/blog/codex-todo-mvc"  class="text-gray-800">[blog post]</a>
        <a href="https://github.com/sturdy-dev/codeball-todo-mvc"  class="text-gray-800">[sources]</a>
    </p>
</div>